### ISSUE TITLE
KeyError: 'DP-2-2' in is_equal_configuration

### ISSUE THREAD

**Issue by blueyed** [phillipberndt/autorandr#109]
Just got this KeyError when connecting a screen:

```
systemd[1]: Starting autorandr execution hook...
autorandr[8178]: Unhandled exception ('DP-2-2'). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
autorandr[8178]: autorandr running as user daniel (started from batch instance)
autorandr[8178]: Traceback (most recent call last):
autorandr[8178]:   File "/usr/bin/autorandr", line 1342, in <module>
autorandr[8178]:     exception_handled_main()
autorandr[8178]:   File "/usr/bin/autorandr", line 1326, in exception_handled_main
autorandr[8178]:     main(sys.argv)
autorandr[8178]:   File "/usr/bin/autorandr", line 1231, in main
autorandr[8178]:     configs_are_equal = is_equal_configuration(config, profiles[profile_name]["config"])
autorandr[8178]:   File "/usr/bin/autorandr", line 764, in is_equal_configuration
autorandr[8178]:     if (output in source_configuration or "off" not in source_configuration[output].options):
autorandr[8178]: KeyError: 'DP-2-2'
autorandr[8178]: Unhandled exception ('DP-2-2'). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
autorandr[8178]: autorandr running as user daniel (started from batch instance)
autorandr[8178]: Traceback (most recent call last):
autorandr[8178]:   File "/usr/bin/autorandr", line 1342, in <module>
autorandr[8178]:     exception_handled_main()
autorandr[8178]:   File "/usr/bin/autorandr", line 1326, in exception_handled_main
autorandr[8178]:     main(sys.argv)
autorandr[8178]:   File "/usr/bin/autorandr", line 1231, in main
autorandr[8178]:     configs_are_equal = is_equal_configuration(config, profiles[profile_name]["config"])
autorandr[8178]:   File "/usr/bin/autorandr", line 764, in is_equal_configuration
autorandr[8178]:     if (output in source_configuration or "off" not in source_configuration[output].options):
autorandr[8178]: KeyError: 'DP-2-2'
```

autorandr 1.5 (git via Arch package IIRC)

**Comment by phillipberndt** [comment]
Dang.. I already fixed this, but apparently forgot to upload the patch. Will push as soon as possible :/

**Comment by blueyed** [comment]
Great!
I am glad that you need no further info.. :)

**Comment by phillipberndt** [comment]
Should be fixed in latest master now.
