### ISSUE TITLE
Regexp fails for negative gamma

### ISSUE THREAD

**Issue by suuuehgi** [phillipberndt/autorandr#188]
> Please report this as a bug at https://github.com/phillipberndt/autorandr/issues

```
> autorandr --save docked --force
Unhandled exception (could not convert string to float: ''). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
Traceback (most recent call last):
  File "/home/username/.local/bin/autorandr", line 10, in <module>
    sys.exit(exception_handled_main())
  File "/home/username/.local/lib/python3.8/site-packages/autorandr.py", line 1400, in exception_handled_main
    main(sys.argv)
  File "/home/username/.local/lib/python3.8/site-packages/autorandr.py", line 1218, in main
    config, modes = parse_xrandr_output()
  File "/home/username/.local/lib/python3.8/site-packages/autorandr.py", line 516, in parse_xrandr_output
    output, output_modes = XrandrOutput.from_xrandr_output("".join(split_xrandr_output[i:i + 2]))
  File "/home/username/.local/lib/python3.8/site-packages/autorandr.py", line 385, in from_xrandr_output
    gamma = ":".join([str(max(1e-10, round(1. / float(x), 3))) for x in gamma.split(":")])
  File "/home/username/.local/lib/python3.8/site-packages/autorandr.py", line 385, in <listcomp>
    gamma = ":".join([str(max(1e-10, round(1. / float(x), 3))) for x in gamma.split(":")])
ValueError: could not convert string to float: ''
```

```
> xrandr -q --verbose | grep -i gamma
	Gamma:      -0.51:1.3:inf
```

is being parsed via

```regexp
Gamma: (?P<gamma>(?:inf|[0-9\.: e])+)
```

(not taking the minus into consideration) to:

```python
match['gamma'] = None
```

If you add the minus, it works:

```regexp
176: Gamma: (?P<gamma>(?:inf|[0-9\.: e-])+)
```

```
> autorandr --version
autorandr 1.9
```

**Comment by phillipberndt** [comment]
Negative gamma values.. now that's interesting :-) What's the visible effect of that?

Could you file your change as a PR, please?
