### ISSUE TITLE
Unhandled exception (local variable 'index' referenced before assignment)

### ISSUE THREAD

**Issue by phijor** [phillipberndt/autorandr#190]
Running `autorandr -c` from `master` fails with the following error:

```
Unhandled exception (local variable 'index' referenced before assignment). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
Traceback (most recent call last):
  File "<venv>/bin/autorandr", line 11, in <module>
    load_entry_point('autorandr', 'console_scripts', 'autorandr')()
  File "/tmp/autorandr/autorandr.py", line 1455, in exception_handled_main
    main(sys.argv)
  File "/tmp/autorandr/autorandr.py", line 1375, in main
    if ("-c" in options or "--change" in options) and index < best_index:
UnboundLocalError: local variable 'index' referenced before assignment
```
This happens here I guess:

https://github.com/phillipberndt/autorandr/blob/cde6a0e940d736a84ff1390d3306794e1ee49627/autorandr.py#L1375

I bisected the issue between 0ebfa82 (current `HEAD`) and `1.9`, and it seems like the issue was introduced in 0bbdbd0b1a7:

```diff
0bbdbd0b1a7e98dd89112a74110dbc6ee8112021 is the first bad commit
commit 0bbdbd0b1a7e98dd89112a74110dbc6ee8112021
Author: Phillip Berndt <phillip.berndt@googlemail.com>
Date:   Sat Apr 11 14:11:31 2020 +0200

    Sort approximate matches in detected profiles by quality of match

    See #189

 README.md    |  1 +
 autorandr.py | 42 +++++++++++++++++++++++++++++++++++-------
 2 files changed, 36 insertions(+), 7 deletions(-)
```

**Comment by phillipberndt** [comment]
Oops. Thanks for reporting this! Fixed.
