### ISSUE TITLE
Unhandled exception (non-hexadecimal number found in fromhex() ...)

### ISSUE THREAD

**Issue by samcoult** [phillipberndt/autorandr#302]
```
samcoult@laptop:~$ autorandr --debug
Unhandled exception (non-hexadecimal number found in fromhex() arg at position 0). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
Traceback (most recent call last):
  File "/usr/bin/autorandr", line 1646, in <module>
    exception_handled_main()
  File "/usr/bin/autorandr", line 1630, in exception_handled_main
    main(sys.argv)
  File "/usr/bin/autorandr", line 1425, in main
    ignore_lid=ignore_lid,
  File "/usr/bin/autorandr", line 603, in parse_xrandr_output
    output, output_modes = XrandrOutput.from_xrandr_output("".join(split_xrandr_output[i:i + 2]))
  File "/usr/bin/autorandr", line 466, in from_xrandr_output
    return XrandrOutput(match["output"], edid, options), modes
  File "/usr/bin/autorandr", line 322, in __init__
    self.parse_serial_from_edid()
  File "/usr/bin/autorandr", line 330, in parse_serial_from_edid
    raw = bytes.fromhex(self.edid)
ValueError: non-hexadecimal number found in fromhex() arg at position 0

samcoult@laptop:~$ autorandr --version
autorandr 1.12.1
samcoult@laptop:~/test$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
samcoult@laptop:~/test$ python --version
Python 2.7.17
samcoult@laptop:~/test$ python3 --version
Python 3.6.9
samcoult @ laptop:~ $ xrandr --version
xrandr program version       1.5.0
Server reports RandR version 1.5

samcoult @ laptop:~ $ xrandr
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-1-3 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 596mm x 336mm
   2560x1440     59.95*+ 144.01   120.00    99.95  
   3840x2160     60.00    50.00    59.94  
   1920x1080    120.04    99.99   120.00   119.88    60.00    50.00    30.00    29.97  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1440x576      50.00  
   1024x768      75.03    70.07    60.00  
   1440x480      60.00    59.94  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
```

`~/.config/autorandr` directory attached
[autorandr.tar.gz](https://github.com/phillipberndt/autorandr/files/9641517/autorandr.tar.gz)

`xrandr -q --verbose` output attached
[xrandr_verbose_output.txt](https://github.com/phillipberndt/autorandr/files/9642751/xrandr_verbose_output.txt)

**Comment by samcoult** [comment]
Did some debugging.

My laptop was a in weird state where there was a bugged out DP-1-3 instance that was sort of "half connected". After disconnecting the monitor I was unable to use `arandr` to add it back to the configuration as `xrandr` was returning errors about bad values.

This PR #303 fixed the error in `autorandr`, but I'm not sure if that's the appropriate way to handle this case anyway. After this fix `autorandr` was unable to match to the preexisting saved configurations (the EDID serial did not match). It would probably be better to log some sort of error message.

After restarting my laptop `autorandr`/`arandr`/`xrandr` all work as expect, the above PR was not necessary.

**Comment by phillipberndt** [comment]
Yes, that's the right fix. Thanks!
