### ISSUE TITLE
Unhandled exception (local variable 'output' referenced before assignment)

### ISSUE THREAD

**Issue by multiplie-fr** [phillipberndt/autorandr#367]
Unhandled exception (local variable 'output' referenced before assignment). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
Traceback (most recent call last):
  File "/usr/local/bin/autorandr", line 8, in <module>
    sys.exit(exception_handled_main())
  File "/usr/local/lib/python3.9/dist-packages/autorandr.py", line 1686, in exception_handled_main
    main(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/autorandr.py", line 1564, in main
    detected_profiles = find_profiles(config, profiles)
  File "/usr/local/lib/python3.9/dist-packages/autorandr.py", line 769, in find_profiles
    closeness = max(match_asterisk(output.edid, current_config[name].edid), match_asterisk(
UnboundLocalError: local variable 'output' referenced before assignment

**Comment by multiplie-fr** [comment]
--save works but when I try to load or just type autorandr I get that message.
