### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by somini** [phillipberndt/autorandr#66]
I'm running Arch Linux with the latest autorandr-git AUR package.

Here's the journal log
```
#STUFF# systemd[1]: Starting autorandr execution hook...
#STUFF# autorandr[4734]: Unhandled exception (str expected, not int). Please report this as a bug at https://github.com/phillipberndt/autorandr/issues.
#STUFF# autorandr[4734]: Running autorandr as somini for display :0
#STUFF# autorandr[4734]: Traceback (most recent call last):
#STUFF# autorandr[4734]:   File "/usr/bin/autorandr", line 1090, in <module>
#STUFF# autorandr[4734]:     exception_handled_main()
#STUFF# autorandr[4734]:   File "/usr/bin/autorandr", line 1077, in exception_handled_main
#STUFF# autorandr[4734]:     main(sys.argv)
#STUFF# autorandr[4734]:   File "/usr/bin/autorandr", line 890, in main
#STUFF# autorandr[4734]:     dispatch_call_to_sessions([ x for x in argv if x != "--batch" ])
#STUFF# autorandr[4734]:   File "/usr/bin/autorandr", line 868, in dispatch_call_to_sessions
#STUFF# autorandr[4734]:     os.environ.update(process_environ)
#STUFF# autorandr[4734]:   File "/usr/lib/python3.6/_collections_abc.py", line 841, in update
#STUFF# autorandr[4734]:     self[key] = other[key]
#STUFF# autorandr[4734]:   File "/usr/lib/python3.6/os.py", line 674, in __setitem__
#STUFF# autorandr[4734]:     value = self.encodevalue(value)
#STUFF# autorandr[4734]:   File "/usr/lib/python3.6/os.py", line 742, in encode
#STUFF# autorandr[4734]:     raise TypeError("str expected, not %s" % type(value).__name__)
#STUFF# autorandr[4734]: TypeError: str expected, not int
#STUFF# autorandr[4734]: Running autorandr as somini for display :0
#STUFF# systemd[1]: Started autorandr execution hook.
```

**Comment by phillipberndt** [comment]
Thanks. My bad - applied the obvious fix.
